license:
  mit: "https://raw.githubusercontent.com/github/choosealicense.com/gh-pages/_licenses/mit.txt"
  apache: "https://raw.githubusercontent.com/github/choosealicense.com/gh-pages/_licenses/apache-2.0.txt"
  bsd-3-clause: "https://raw.githubusercontent.com/github/choosealicense.com/gh-pages/_licenses/bsd-3-clause.txt"

gitignores:
  go: "https://raw.githubusercontent.com/github/gitignore/main/Go.gitignore"
  python: "https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore"
  ansible: "https://raw.githubusercontent.com/ansible/ansible/devel/.gitignore"
  terraform: "https://raw.githubusercontent.com/github/gitignore/main/Terraform.gitignore"
